services:
  wordpress:
    labels:
      traefik.enable: 'true'
      traefik.http.routers.wordpress.rule: 'Host(`${WORDPRESS_DOMAIN}`) || Host(`www.${WORDPRESS_DOMAIN}`)'
      traefik.http.routers.wordpress.tls: 'true'
      traefik.http.routers.wordpress.tls.certresolver: 'letsencrypt'
      traefik.http.routers.wordpress.service: "wordpress"
      traefik.http.services.wordpress.loadbalancer.server.scheme: "http"
      traefik.http.services.wordpress.loadbalancer.server.port: "80"
  traefik:
    image: traefik:v3.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesResolvers.letsencrypt.acme.email=${ACME_MAIL}"
      - "--certificatesResolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesResolvers.letsencrypt.acme.httpChallenge.entryPoint=web"
    ports:
      # not needed, we use the dns challenge
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
volumes:
  letsencrypt:
